### ISSUE TITLE
Create Tag, Revit 2023

### ISSUE THREAD

**Issue by Plarmindo** [albandechasteigner/GeniusLociForDynamo#21]
Hi Alban, first of all, thanks for sharing all your nodes, they are excellent.
I have been testing rebar on Revit 2023, and your node for creating tags doesn't work with rebar.
Is this something that you are available to fix?

Regards

Paulo Lima

**Comment by albandechasteigner** [comment]
Hi Paulo,
There was a change in the Revit 2023 API for rebars. 
By the way, the OOTB Tag.ByElement nodes haven't been updated and don't work either.
You are lucky because I saw this change yesterday and fixed it.
The updated node can be [donwloaded](https://github.com/albandechasteigner/GeniusLociForDynamo/blob/master/Nodes/Create%20Tag.dyf) and the old node replaced in C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\2.16\packages\Genius Loci\dyf
(You need to click the Raw button and right click save as to properly download the custom node.)
Best regards,

**Comment by bminkov97** [comment]
Hi Alban, 
Great work! I have tried tagging the rebars in my slab but it seems that the rebar element I selected does not have the GetSubelements attribute (you use it at line 239 of your code). I tried it with PathReinforcement element and it does not seem to work. Any ideas? 

Thanks in advance
Regards
Boris M

**Comment by bminkov97** [comment]
@albandechasteigner
