### ISSUE TITLE
Link IFC results in null in revit 2023

### ISSUE THREAD

**Issue by BertusRevit** [albandechasteigner/GeniusLociForDynamo#29]
Dynamo Revit 2.13.1.3891
Genius Loci 2023.7.13
DynamoIronPython2.7 2.1.0

In revit 2022 works perfect only in revit 2023 not. What's wrong?

![2023-11-16 13_05_25-Window](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/151031782/7aa10e27-622a-4717-a724-bc9ed7733a68)

**Comment by albandechasteigner** [comment]
Hi,

It is working for me with Revit 2023. Not sure where your issue is.
![Revit 2023](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/67761287/fbc6b586-9ad1-4990-9506-d0f18a81aefc)
![IFC 2023](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/67761287/f6e94606-8d0c-492b-9173-2f7d2da6a6c9)

**Comment by Cyberflow187** [comment]
HI all,

I've got the same issue too : 
![image](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/7341949/1257411b-aec7-4090-81fa-f997c4031ea3)
![image](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/7341949/68e0037d-c616-49ff-b677-d25a5e630644)

Not sure what is happening

My packages seem ok too : 

![image](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/7341949/f1bf790c-1eb5-429a-9ce2-94bd42617c99)

**Comment by albandechasteigner** [comment]
Link to discussion added: https://forum.dynamobim.com/t/importing-ifc-files-in-bulk-with-dynamo-into-revit/102060/4
